// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcuhvqemmkghjauefzdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjdWh2cWVtbWtnaGphdWVmemR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwNTY0MTcsImV4cCI6MjA1MjYzMjQxN30.28g7nU211yxsvZihL4Py138VFqfk41vtKsNOKZlftak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);